#!/usr/bin/env bash
ls source > /dev/null
ls ~/.ssh > /dev/null
git --version > /dev/null
chmod 400 ./source/id_rsa > /dev/null
cp ./source/config ~/.ssh/config > /dev/null
git clone --quiet git@github.com:macedo22/autograder-demo.git > /dev/null
rm ./source/id_rsa
bash autograder-demo/ucsd-cse599-pa1-grading/grade
